name: 'create bee'
description: 'Creates a bee for the Teaspoons e2e test'
inputs:
  token:
    description: 'The auth token to use for bee creation'
    required: true
    type: string
  bee_name:
    description: 'The name of the bee to create'
    required: true
    type: string
  run_name:
    description: 'Specify the run name to fetch the run ID based on the actual run name'
    required: false
    type: string
  custom_version_json:
    description: 'json containing custom versions to push. e.g. {"teaspoons":{"appVersion":"0.0.81-66ceced"}}'
    required: false
    type: string
  version-template:
    description: 'version template to copy. defaults to dev'
    default: 'dev'
    required: true
    type: choice
    options:
      - dev
      - staging
      - prod

runs:
  using: 'composite'
  steps:
    - name: dispatch to terra-github-workflows
      uses: broadinstitute/workflow-dispatch@v4
      with:
        workflow: bee-create
        repo: broadinstitute/terra-github-workflows
        ref: refs/heads/main
        token: '${{ inputs.token }}'
        inputs: >-
          { 
          "run-name": "${{ inputs.run_name }}",
          "bee-name": "${{ inputs.bee_name }}", 
          "bee-template-name": "teaspoons-e2e-gcp-tests", 
          "version-template": "${{ inputs.version-template }}",
          "custom-version-json": "${{ inputs.custom_version_json }}"
          }
