name: Bump, Tag, Test, Publish Python CLI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.github/**'
  pull_request:
    branches: [ '**' ]
    # There is an issue with GitHub required checks and paths-ignore. We don't really need to
    # run the tests if there are only irrelevant changes (see paths-ignore above). However,
    # we require tests to pass by making a "required check" rule on the branch. If the action
    # is not triggered, the required check never passes and you are stuck. Therefore, we have
    # to run tests even when we only change a markdown file. So don't do what I did and put a
    # paths-ignore right here!
  workflow_dispatch: {}

jobs:
  bump-check:
    runs-on: ubuntu-latest
    outputs:
      is-bump: ${{ steps.skiptest.outputs.is-bump }}
    steps:
      - uses: actions/checkout@v2
      - name: Skip version bump merges
        id: skiptest
        uses: ./.github/actions/bump-skip
        with:
          event-name: ${{ github.event_name }}

  tag-job:
    needs: [ bump-check ]
    runs-on: ubuntu-latest
    if: needs.bump-check.outputs.is-bump == 'no'
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - name: Set part of semantic version to bump
        id: controls
        run: |
          SEMVER_PART=""
          CHECKOUT_BRANCH="$GITHUB_REF"
          if ${{github.event_name == 'push' }}; then
            SEMVER_PART="patch"
          elif ${{github.event_name == 'workflow_dispatch' }}; then
            SEMVER_PART=${{ github.event.inputs.bump }}
            CHECKOUT_BRANCH=${{ github.event.inputs.branch }}
          fi
          echo ::set-output name=semver-part::$SEMVER_PART
          echo ::set-output name=checkout-branch::$CHECKOUT_BRANCH

      - name: Checkout current code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.controls.outputs.checkout-branch }}
          token: ${{ secrets.BROADBOT_TOKEN }}

      - name: Bump the tag to a new version
        # https://github.com/DataBiosphere/github-actions/tree/master/actions/bumper
        uses: databiosphere/github-actions/actions/bumper@bumper-0.4.0
        id: tag
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
          HOTFIX_BRANCHES: hotfix.*
          OVERRIDE_BUMP: ${{ steps.controls.outputs.semver-part }}
          RELEASE_BRANCHES: main
          VERSION_FILE_PATH: pyproject.toml
          VERSION_LINE_MATCH: "^version\\s*=\\s*\".*\""
          VERSION_SUFFIX: SNAPSHOT

  install-and-test-python-cli:
    needs: [ bump-check ]
    runs-on: ubuntu-latest
    if: needs.bump-check.outputs.is-bump == 'no'
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install the thick CLI
        run: |
          poetry install

      - name: Run linter check (ruff)
        run: |
          poetry run ruff check

      - name: Run tests with coverage, write coverage report to coverage.xml
        run: |
          poetry run pytest --cov-report xml --cov=terralab

      # The SonarQube scan is done here, so it can upload the coverage report generated by the tests.
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish-to-pypi:
    needs: [ bump-check, tag-job, install-and-test-python-cli ]
    uses: ./.github/workflows/publish-cli.yml
    # only run this on push to main, i.e. not on each PR
    if: ${{ github.event_name != 'pull_request' }}

  notify-slack:
    needs: [ bump-check, install-and-test-python-cli ]
    runs-on: ubuntu-latest
    if: failure() && github.event_name == 'push' && needs.bump-check.outputs.is-bump == 'no'

    steps:
      - name: Notify Teaspoons Slack on Failure
        uses: broadinstitute/action-slack@v3.8.0
        # see https://github.com/broadinstitute/action-slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: failure
          channel: "#terra-tsps-alerts"
          username: "Terralab CLI push to main branch"
          author_name: "test-python-cli"
          icon_emoji: ":triangular_ruler:"
          fields: job, commit
