name: Build and publish the CLI to PyPI

on:
  pull_request:
  workflow_call:
    inputs:
      new-tag:
        required: true
        type: string
jobs:
  params-gen:
    runs-on: ubuntu-latest
    outputs:
      new-tag: ${{ steps.generate-params.outputs.new-tag }}
    steps:
      - name: Get inputs or use defaults
        id: generate-params
        run: |
          if [ -z ${{ inputs.new-tag }} ]; then
            echo "No new tag provided; will run through tasks, but ultimately will not overwrite PyPi version '0.0.0'"
            echo "new-tag='0.0.0'" >> $GITHUB_OUTPUT
          else
            echo "New tag provided: ${{ inputs.new-tag }}"
            echo "new-tag=${{ inputs.new-tag }}" >> $GITHUB_OUTPUT
          fi

  build-n-publish:
    name: Build and publish Python client to PyPI
    needs: [ params-gen ]
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing (OIDC)
      # https://docs.pypi.org/trusted-publishers/using-a-publisher/
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build the CLI using poetry
        run: |
          poetry build
      
      - name: Publish the CLI to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          skip_existing: true
